strict: false
site_url: https://openvidu.io/
site_name: OpenVidu Docs
repo_url: https://github.com/OpenVidu/openvidu.io-docs
nav:
- What is OpenVidu?: index.md
- Tutorials:
  - Intro: tutorials/index.md
  - openvidu-webcomponent: tutorials/openvidu-webcomponent.md
  - openvidu-hello-world: tutorials/openvidu-hello-world.md
  - openvidu-iframe: tutorials/openvidu-iframe.md
  - openvidu-insecure-js: tutorials/openvidu-insecure-js.md
  - openvidu-insecure-angular: tutorials/openvidu-insecure-angular.md
  - openvidu-library-angular: tutorials/openvidu-library-angular.md
  - openvidu-insecure-react: tutorials/openvidu-insecure-react.md
  - openvidu-library-react: tutorials/openvidu-library-react.md
  - openvidu-insecure-vue: tutorials/openvidu-insecure-vue.md
  - openvidu-ionic: tutorials/openvidu-ionic.md
  - openvidu-react-native: tutorials/openvidu-react-native.md
  - openvidu-android: tutorials/openvidu-android.md
  - openvidu-ios: tutorials/openvidu-ios.md
  - openvidu-electron: tutorials/openvidu-electron.md
  - openvidu-ipcameras: tutorials/openvidu-ipcameras.md
  - openvidu-js-java: tutorials/openvidu-js-java.md
  - openvidu-mvc-java: tutorials/openvidu-mvc-java.md
  - openvidu-js-node: tutorials/openvidu-js-node.md
  - openvidu-mvc-node: tutorials/openvidu-mvc-node.md
  - openvidu-recording-java: tutorials/openvidu-recording-java.md
  - openvidu-recording-node: tutorials/openvidu-recording-node.md
- Demos:
  - openvidu-call: demos/openvidu-call.md
  - openvidu-call-react: demos/openvidu-call-react.md
  - openvidu-call-ionic: demos/openvidu-call-ionic.md
  - openvidu-classroom: demos/openvidu-classroom.md
  - openvidu-getaroom: demos/openvidu-getaroom.md
- Cheatsheet:
  - Join a session: cheatsheet/join-session.md
  - Leave a session: cheatsheet/leave-session.md
  - Subscribe/Unsubscribe from a stream: cheatsheet/subscribe-unsubscribe.md
  - Publish/Unpublish a stream: cheatsheet/publish-unpublish.md
  - Mute/Unmute audio and video: cheatsheet/mute-audio-video.md
  - Manage video players: cheatsheet/manage-videos.md
  - Share data between users: cheatsheet/share-data.md
  - Send text messages: cheatsheet/send-messages.md
- Advanced features:
  - Recording: advanced-features/recording.md
  - Screen share: advanced-features/screen-share.md
  - IP cameras: advanced-features/ip-cameras.md
  - Speech detection: advanced-features/speech-detection.md
  - Voice and video filters: advanced-features/filters.md
  - Switch camera: advanced-features/switch-camera.md
  - Automatic reconnection: advanced-features/automatic-reconnection.md
  - Network quality: advanced-features/network-quality.md
- Reference Documentation:
  - openvidu-browser API: reference-docs/openvidu-browser.md
  - openvidu-java-client API: reference-docs/openvidu-java-client.md
  - openvidu-node-client API: reference-docs/openvidu-node-client.md
  - REST API: reference-docs/REST-API.md
  - OpenVidu configuration: reference-docs/openvidu-config.md
  - OpenVidu CDR: reference-docs/openvidu-server-cdr.md
  - OpenVidu Webhook: reference-docs/openvidu-server-webhook.md
- Deployment:
  - Intro: deployment/index.md
  - AWS: deployment/deploying-aws.md
  - On premises: deployment/deploying-on-premises.md
  - Deploying OpenVidu applications: deployment/deploying-openvidu-apps.md
  - Upgrading OpenVidu: deployment/upgrading.md
- Contribute:
  - Developing OpenVidu: developing/index.md
  - OpenVidu Server RPC protocol: developing/rpc.md
- Troubleshooting / FAQ: troubleshooting/index.md
- Releases: releases/index.md
- OpenVidu Pro:
  - Home: openvidu-pro/index.md
  - Scalability: openvidu-pro/scalability.md
  - OpenVidu Inspector: openvidu-pro/openvidu-inspector.md
  - Monitoring - Elastic Stack: openvidu-pro/monitoring-elastic-stack.md
  - Deployment:
    - AWS: openvidu-pro/deployment/aws.md
    - On premises: openvidu-pro/deployment/on-premises.md
    - Upgrading OpenVidu Pro: openvidu-pro/deployment/upgrading.md
docs_dir: docs
theme:
    name: mkdocs
    custom_dir: custom_theme

markdown_extensions:
  - markdown.extensions.extra
  - toc:
        permalink: " ðŸ”—"